try:
    contador= 0

    divisao = 4 / contador

    print('Teste 1')
except Exception as e:
    print(f'Ocorreu um erro de: {e} .. tente novamente')
print('Teste 2')
